version: '2'

volumes:
  nextcloud:
  db-nextcloud:

services:
  db-nextcloud:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${DOCKERSTORAGEDIR}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:80
    links:
      - db-nextcloud
    volumes:
      - ${DOCKERSTORAGEDIR}/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db-nextcloud
	  
	  
	  
	  
***************************************************env*********************
DOCKERHOSTNAME='MANOJ_SERVER'
DOCKERCONFDIR='/home/pi/.config/appdata'
DOCKERSTORAGEDIR='/mnt/hdd/NAS/DockerFiles/storage'
DOCKERGID='999'
PGID='1000'
PUID='1000'
TZ='Asia/Kolkata'
NEXTCLOUD_PORT='8881'