version: '2'

networks:
  npm:
  
volumes:
  nginx:
  db-nginx:
  
services:
  db-nginx:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${DOCKERSTORAGEDIR}/nginx/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nginx
      - MYSQL_USER=nginx
      
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
       # These ports are in format <host-port>:<container-port>
      - ${NGINX_HTTP_PORT}:80 # Public HTTP Port
      - ${NGINX_HTTPS_PORT}:443 # Public HTTPS Port
      - ${NGINX_ADMIN_PORT}:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    links:
      - db-nginx
    volumes:
      - ${DOCKERSTORAGEDIR}/nginx/data:/data
      - ${DOCKERSTORAGEDIR}/nginx/letsencrypt:/etc/letsencrypt
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nginx
      - MYSQL_USER=nginx
      - MYSQL_HOST=db
    
    depends_on:
      - db-nginx

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    networks:
      - npm
    volumes:
      - ${DOCKERSTORAGEDIR}/vaultwarden:/data/
    ports:
      - ${VALTWARDEN_PORT}:80
    restart: unless-stopped
    
****************************************ENV*************************
DOCKERHOSTNAME='MANOJ_SERVER'
DOCKERCONFDIR='/home/pi/.config/appdata'
DOCKERSTORAGEDIR='/mnt/hdd/NAS/DockerFiles/storage'
DOCKERGID='999'
PGID='1000'
PUID='1000'
TZ='Asia/Kolkata'
NGINX_HTTP_PORT='80'
NGINX_HTTPS_PORT='443'
NGINX_ADMIN_PORT='82'
VALTWARDEN_PORT='8006'